name: Build Develop
on: 
  push:
    branches:
      - main

env:
  ECR_DOMAIN: huynhvu411
  ECR_REPO: taipy_python

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"  

        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_DOMAIN/$ECR_REPO:${{ steps.prep.outputs.BUILD_ID }} . --no-cache
          docker push $ECR_DOMAIN/$ECR_REPO:${{ steps.prep.outputs.BUILD_ID }} .